### ISSUE TITLE
Filename doesn't contain any special characters... rejected for containing special characters

### ISSUE THREAD

**Issue by lansdell-hs** [ISA-tools/ISAcreator#319] opened 2017-06-21 15:02 UTC
In ISAcreator, I am attempting to create a new study by mapping from an existing file. The application is rejecting my .csv file, saying "filenames must not contain any special characters such as &, :, ?, *, |, :, please select a different file or rename it..."

My filename is BXDNACSscores.csv. I understand the "." in .csv is there, but I can hardly remove the extension with jeopardizing the file.

**Comment by proccaserra** [comment] 2017-06-21 15:11
Hi @spencerhb , can you provide us with information about ISAcreator version, Operating System and java version you are currently running?

also, if you run the tool from the command line, did you see any error ? any stack trace you could send us?

Alternately, you may wish to provide us with the file you are using so we can try on our end

**Comment by spencerhb** [comment] 2017-06-21 15:22
I downloaded the jar java application, so I'm not running from command line. I am running it on windows 10 with java 8.

**Comment by proccaserra** [comment] 2017-06-21 15:32
can you send us the offending file to isatools@googlegroups.com (private list) ? if the data is sensitive, would you mind sending the first 2 lines of the file to rule out any thing non data related?
thx

**Comment by spencerhb** [comment] 2017-06-21 15:37
File has been sent

**Comment by proccaserra** [comment] 2017-06-21 15:49
ok, works fine on our end:
![image](https://user-images.githubusercontent.com/517736/27393299-d385c29a-56a0-11e7-856c-905719b57061.png)

![image](https://user-images.githubusercontent.com/517736/27393347-f91ddee8-56a0-11e7-8935-b257790fcecc.png)

This points to a windows specific issue. I am running ISAcreator-1.7.9 with the default configuration

So it brings my question: the file you sent corresponds to an Affymetrix summarization file (possibly GC-RMA or similar) and therefore holds no metadata to map into ISA syntax. 
So the mapper would not help you that much. Do you have a study metadata file?
What you would need is a spreadsheet describing what BXD\d+ are, and any information about array design, software processing and so on.

hth

**Comment by spencerhb** [comment] 2017-06-21 15:54
I do have an annotation file. I was more trying to play with the mapper and that was a file I had at hand. I am running ISA 1.7.9 with default configuration.

**Comment by proccaserra** [comment] 2017-06-21 20:27
ok good. can you open a terminal / command line, navigate to the folder where isacreator is installed and run the following command:
>java -jar -Xms256m -Xmx1024m ISAcreator-1.7.9.jar

in so doing, you will be able to see any error message the tool may throw as it tries to read the csv file.

let us know how it is going on.

Another thing to try: saving the file as utf-8 again with windows line endings (I am trying to rule out any character encoding issue which may still arise when moving between OS).

**Comment by spencerhb** [comment] 2017-06-21 21:06
I received the same error, but I don't see any error message in command..... I received the same error with the file as Unicode.  The command line merely said this after loading the default configuration and selecting create new experiment: 
Loaded configuration
============Hiding glass pane
removing current page...

**Comment by djcomlab** [comment] 2017-06-22 08:08
Hi Heather - I'm David and am another developer in the ISA tools team. I have a Windows 10 box I can test this on, so will see if I can help you out. Will get back to you asap!

**Comment by djcomlab** [comment] 2017-06-22 08:20
Hi Heather, just looking back to the original issue - the error is "filenames must not contain any special characters such as &, :, ?, *, |, :, please select a different file or rename it...", but the filename "BXDNACSscores.csv" should therefore be valid.

However it could imply special characters are used in the full path to the file - can you confirm that there's no special characters in the full path (perhaps in a directory name in the path) to your file?

**Comment by spencerhb** [comment] 2017-06-22 12:46
I cannot remove the ":" that comes after the C in the path that specifies which hard drive I'm working on... That's the only special character in the path.  I've tried a different file now (annotation file) and am getting the same error. 
Full path 
C:\Users\H\Desktop\Mouse430 2.na35.annot.csv

**Comment by spencerhb** [comment] 2017-06-23 13:29
My work computer is back up (a mac) and I am not having this issue there, so I know it isn't my annotation file causing the issue. I still want to figure out the problem.

**Comment by djcomlab** [comment] 2017-06-23 13:32
Hiya, I can confirm this is indeed a bug - in the source code the check on the filename that looks for the special characters actually checks the full path, not just the filename, so is likely detecting the colons used in Windows drive paths.

I believe this is where the problem is and I'm working on a fix.

**Comment by spencerhb** [comment] 2017-06-23 13:34
Thanks very much and keep me updated! I'm trying to learn the system so I can demo it to others.

**Comment by lansdell-hs** [comment] 2017-07-10 14:06
Is there any movement on this bug? Thanks!

**Comment by djcomlab** [comment] 2017-07-11 06:48
Hi Heather, thanks for following up - I've got a fix ready, but just need to address a couple of other outstanding bugs to fix to push out in the next build. I'm hoping to have that build released by the end of this week and will let you know when it's out.

Please feel free to ping me again if you don't hear anything!

**Comment by djcomlab** [comment] 2017-07-27 16:01
Fixed in development branch, fix will be pushed out in next release.

**Closed by djcomlab** 2017-07-27 16:01 UTC
Labels: Mapper, Minor Bug
