### ISSUE TITLE
Unable to add assays with ISAcreator 1.7.9 on Mac OS X 10.12.3

### ISSUE THREAD

**Issue by tomsing1** [ISA-tools/ISAcreator#313] opened 2017-02-17 03:34 UTC
Dear ISA team,

I am trying to make my first steps with the [jar file](https://github.com/ISA-tools/ISAcreator/releases/download/1.7.9/ISAcreator-macOS.dmg)  of  ISAcreator 1.7.9 (light) on Mac OS X 10.12.3. I am using java version `1.8.0_111`

```
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

I have created a study using the default config and would like to add a first assay. Yet, once I have picked the assay to add, I am unable to `confirm` the selected assays. After pressing the `confirm` button, the following error is shown in the command line:

```
Loaded configuration
============Hiding glass pane
Should I always show the investigation? false
============Hiding glass pane
removing current page...
Data entry panel changed & initialised
Should I always show the investigation? false
Measurement is transcription profiling technology is: DNA microarray
Hopefully it isn't present: true
Getting assay for measurement transcription profiling and technology DNA microarray
_____populateAcceptedOntologies()____
Unable to get ontologies. Please check the internet connection.
java.lang.String cannot be cast to net.minidev.json.JSONArray
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.isatools.isacreator.ontologymanager.OntologySourceRefObject.completeFields(OntologySourceRefObject.java:100)
	at org.isatools.isacreator.ontologymanager.OntologySourceRefObject.<init>(OntologySourceRefObject.java:70)
	at org.isatools.isacreator.model.Assay.<init>(Assay.java:133)
	at org.isatools.isacreator.gui.DataEntryEnvironment.addAssay(DataEntryEnvironment.java:151)
	at org.isatools.isacreator.gui.StudyDataEntry$AddAssayListener.propertyChange(StudyDataEntry.java:784)
	at org.isatools.isacreator.common.WeakPropertyChangeListener.propertyChange(WeakPropertyChangeListener.java:26)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
	at java.awt.Component.firePropertyChange(Component.java:8448)
	at org.isatools.isacreator.assayselection.AssaySelectionDialog.access$700(AssaySelectionDialog.java:69)
	at org.isatools.isacreator.assayselection.AssaySelectionDialog$4.actionPerformed(AssaySelectionDialog.java:171)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by agbeltran** [comment] 2017-02-17 16:16
Thanks for the report @tomsing1, we will investigate.

**Comment by agbeltran** [comment] 2017-02-17 16:40
According to the error message, it seems it was a problem with your internet connection, as ISAcreator downloads info about the ontologies in BioPortal. Where you online when trying this? We will look at improving the error message in this case.

**Comment by tomsing1** [comment] 2017-02-17 17:06
Thanks a lot for following up on this. I also suspected that I might not be able to connect to a remote source and tested it in three different locations (at work, through a public wifi and tethering through my phone). The result was always the same (with the error message I posted above). 

Perhaps you can share a url that I could test outside of ISAcreator to verify that I can connect to the remote source?

Thanks a lot!
Thomas

**Comment by proccaserra** [comment] 2017-02-17 17:39
@tomsing1 Many thanks for reporting. That's an interesting one. The release is indeed broken :( .
I have now ruled out the dmg distribution and being offline. 
The pre-release version I had tested worked as expected. The pb iso be down to a call to an ontology method, so we'll look at how the current released versions pings Bioportal or OLS. We'll get back to asap!

**Comment by djcomlab** [comment] 2017-02-20 11:06
Confirmed; I also managed to replicate this. It looks like ISAcreator caches ontology info on first add of assays, so needs to be connected to Internet on first time.

**Comment by proccaserra** [comment] 2017-02-22 16:58
@tomsing1 following-up: the jar can be used, I wasn't patient enough. As pointed out by @djcomlab, ISAcreator needs to pull ontologies. If offline this does not happen and the tool throws the error you saw. Getting back online, trying to add an assay and the clicking on 'confirm' seems to cause no action but things are happening in the background. So you'd need to wait for 40 sec or so, and the terminal should show something like this:
Loaded configuration
============Hiding glass pane
Should I always show the investigation? false
============Hiding glass pane
removing current page...
Data entry panel changed & initialised
Should I always show the investigation? false
Measurement is transcription profiling technology is: DNA microarray
Hopefully it isn't present: true
Getting assay for measurement transcription profiling and technology DNA microarray
_____populateAcceptedOntologies()____
Found 617 ontologies

then the assay table should be added and visible.

let us know if it works for you.
cheers
P

**Comment by djcomlab** [comment] 2017-07-27 22:14
Closing, as per @proccaserra's workaround.

**Closed by djcomlab** 2017-07-27 22:14 UTC
Labels: Minor Bug
